<?php
require "fonctions.php";
/////////////////////////////////// EXO 1 /////////////////////////////////// 
// Déclaration de variables...
$end=0; // variable fin de boucle
// Début prog...
echo str_repeat(" ", 20).str_repeat("*", 20)."\n".str_repeat(" ", 20)."CALCUL SUR LE CERCLE\n".str_repeat(" ", 20).str_repeat("*", 20)."\n\n"; // Echo Head... str_repeat pour spam des caractères...
while($end!=1){ // Lancement boucle...
    $rayon = readline("Quel est le rayon du cercle : "); // Demande le rayon du cercle à l'utilisateur...
    calculCercle($rayon); // Fonction pour calculer la circonférence et la surface du cercle...
    $reply = readline("Voulez-vous faire un autre calcul (O/N) : "); // Demande si l'utilisateur veut un autre calcul...
    if($reply == "N"){ // Analyse de la réponse utilisateur si non...
        $end++; // Incrémentation de ma variable fin de boucle pour en sortir et terminer le programme...
        echo "\nAu revoir et à bientôt"; // Au revoir...
    } 
    else echo "\n"; // Si oui...
} // Fin boucle...
// Fin prog...
?>