<?php
require "fonctions.php";
/////////////////////////////////// EXO 2 /////////////////////////////////// 
// Déclaration de variables...
$end=0; // variable fin de boucle
// Début prog...
echo str_repeat(" ", 15).str_repeat("*", 7)."   Table de Multiplication   ".str_repeat("*", 7)."\n\n"; // Echo Head... str_repeat pour spam des caractères...
while($end!=1){ // Lancement boucle...
    $nb = (int) readline("Entrer le nombre pour lequel vous voulez la table de multiplication : ");
    echo "\n";
    tableMultiply($nb);
    echo "\n";
    $reply = readline("Voulez-vous continuer ? "); // Demande si l'utilisateur veut un autre calcul...
    if($reply == "N" || $reply == "n"){ // Analyse de la réponse utilisateur si non...
        $end++; // Incrémentation de ma variable fin de boucle pour en sortir et terminer le programme...
    } 
    else if($reply == "O" || $reply == "o") echo "\n"; // Si oui...
} // Fin boucle...
// Fin prog...
?>